services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: msearch-php
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    # In local development, we want to run only php, so we use the built-in server instead of fpm
    command: php -S 0.0.0.0:8000 -t public/
    depends_on:
      - ollama

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16.2-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data: ###< doctrine/doctrine-bundle ###
  ollama_data:
