# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(AI_PROVIDER): 'gemini'
    env(GEMINI_API_KEY): ''
    env(OLLAMA_BASE_URL): 'http://host.docker.internal:11434'
    env(OLLAMA_MODEL): 'minicpm-v:8b-2.6-q3_K_L'
    product_uploads_directory: '%kernel.project_dir%/public/uploads/products'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\GeminiService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
            $aiProvider: '%env(AI_PROVIDER)%'
            $ollamaBaseUrl: '%env(OLLAMA_BASE_URL)%'
            $ollamaModel: '%env(OLLAMA_MODEL)%'

    App\Service\FileUploader:
        arguments:
            $productUploadsDirectory: '%product_uploads_directory%'
